change nestjs to 8
skunight/nestjs-redis pull request #88
Opened 2021-09-09 09:55 UTC by KenChanSwivel

2021-09-09 09:56 UTC, KenChanSwivel commented
Please upgrade nest js version so the one who are using nestjs 8 can be no problem. I have tested on our side.

2021-09-17 12:09 UTC, valentinarodrigues commented
Facing issue with this package when upgrading to nestjs 8. Can we please merge this?

2021-09-29 19:24 UTC, UziTech requested changes

2021-09-29 19:24 UTC, UziTech commented on package.json
> +    "url": "https://github.com/swivelsoftware/nestjs-redis.git"
These changes should be removed from this PR

2022-09-06 13:20 UTC, KenChanSwivel commented
please use this one
https://github.com/skunight/nestjs-redis/pull/104

2022-09-06 13:20 UTC, closed without merging